#!/bin/sh

fail() {
	printf "\033[1m\033[31m[ FAIL ]\033[0m %s\n" "$1"
	exit 1
}

info() {
	printf "\033[1m\033[36m[ INFO ]\033[0m %s\n" "$1"
}

command -v pnpm >/dev/null 2>&1 || {
	NVM="${NVM_DIR:-"$HOME/.nvm"}/nvm.sh"

	[ -f "$NVM" ] || fail "Please install \`pnpm\` globally!"

	. "$NVM" || {
		fail "Please install \`nvm\`!"
	}
}

. "$(dirname "$0")/_/husky.sh"

info "Running \`fmt\` check..."
pnpm run fmt:ci >/dev/null

info "Running \`lint\` check..."
pnpm run lint:ci >/dev/null
