#!/bin/sh

: printing utils
fail() {
	printf "\033[1m\033[31m[ %s ]\033[0m %s\n" "FAIL" "$*"
}

info() {
	printf "\033[1m\033[36m[ %s ]\033[0m %s\n" "INFO" "$*"
}

die() {
	fail "$*"
	exit 1
}

: assert that the pnpm cmd exists
pnpm_installed() {
	if command -v pnpm >/dev/null 2>&1; then
		return 0
	fi
	return 1
}

: assume that pnpm not being installed
: is a result of nvm not being sourced
pnpm_installed || {
	NVM="${NVM_DIR:-"$HOME/.nvm"}/nvm.sh"

	[ -f "$NVM" ] && {
		. "$NVM" ||
			die "Please install \`nvm\` and/or set \`NVM_DIR\` correctly!"
	}
}

: ensure that pnpm was found
pnpm_installed || {
	die "\`pnpm\` has not been installed globally, please do so!"
}

: invoke husky git hook helper
. "$(dirname "$0")/_/husky.sh"

: begin repository checks concurrently
{
	info "Running \`fmt\` check..."
	pnpm run fmt:ci >/dev/null
} &

{
	info "Running \`lint\` check..."
	pnpm run lint:ci >/dev/null
} &

wait && info "Done!"
